### ISSUE TITLE
您好，请问test image是不是给的有点问题啊

### ISSUE THREAD

**Issue by tianshihe** [rolandying/FusionLane#4]
下载下来后label和region文件夹里面的图像都是全黑的

**Comment by rolandying** [comment]
因为像素值就是对应类型的编号，0，1，2，3，4......当然是黑的啊，你可以着色

**Comment by tianshihe** [comment]
感谢！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月15日 17:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [rolandying/FusionLane] 您好，请问test image是不是给的有点问题啊 (Issue #4) |

Closed #4.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
